{% set name = "pyibs" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyIBS-{{ version }}.tar.gz
  sha256: a89670027e8e5bb59c5b7f994625c93c3b4b134e4dfd04e21edf4fc923248a5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - cma >=3.1.0
    - corner >=2.2.1
    - dill >=0.3.5.1
    - gpyreg >=0.1.0
    - imageio >=2.13.5
    - matplotlib-base >=3.5.1
    - numpy >=1.22.1
    - plotly >=5.11.0
    - pytest >=6.2.5
    - pytest-mock >=3.6.1
    - pytest-rerunfailures >=10.2
    - scipy >=1.7.3

test:
  imports:
    - pyibs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/acerbilab/pyibs/
  summary: Inverse Binomial Sampling in Python.
  dev_url: https://github.com/acerbilab/pyibs/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - juls-art
